<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="DemoProject" duration-ms="25727" started-at="2021-04-15T03:03:45Z" finished-at="2021-04-15T03:04:11Z">
    <groups>
    </groups>
    <test name="Tests" duration-ms="25727" started-at="2021-04-15T03:03:45Z" finished-at="2021-04-15T03:04:11Z">
      <class name="com.sample.test.demo.tests.DemoTest">
        <test-method status="PASS" signature="init()[pri:0, instance:com.sample.test.demo.tests.DemoTest@6adede5]" name="init" is-config="true" duration-ms="3864" started-at="2021-04-15T03:03:45Z" finished-at="2021-04-15T03:03:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="demoTest()[pri:0, instance:com.sample.test.demo.tests.DemoTest@6adede5]" name="demoTest" duration-ms="9" started-at="2021-04-15T03:03:49Z" finished-at="2021-04-15T03:03:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoTest -->
        <test-method status="FAIL" signature="orderWithError()[pri:0, instance:com.sample.test.demo.tests.DemoTest@6adede5]" name="orderWithError" duration-ms="10642" started-at="2021-04-15T03:03:49Z" finished-at="2021-04-15T03:04:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Thank you for your order! TOTAL: 13.5 Small 6 Slices - no toppings] but found [Thank you for your order! TOTAL: NaN]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Thank you for your order! TOTAL: 13.5 Small 6 Slices - no toppings] but found [Thank you for your order! TOTAL: NaN]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.sample.test.demo.tests.DemoTest.orderScucess(DemoTest.java:111)
at com.sample.test.demo.tests.DemoTest.orderWithError(DemoTest.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderWithError -->
        <test-method status="PASS" signature="sucessfulOrder()[pri:0, instance:com.sample.test.demo.tests.DemoTest@6adede5]" name="sucessfulOrder" duration-ms="10450" started-at="2021-04-15T03:04:00Z" finished-at="2021-04-15T03:04:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sucessfulOrder -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.sample.test.demo.tests.DemoTest@6adede5]" name="tearDown" is-config="true" duration-ms="717" started-at="2021-04-15T03:04:10Z" finished-at="2021-04-15T03:04:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.sample.test.demo.tests.DemoTest -->
    </test> <!-- Tests -->
  </suite> <!-- DemoProject -->
</testng-results>
